/*
* @Author: Administrator
* @Date:   2017-02-05 20:48:59
* @Last Modified by:   Administrator
* @Last Modified time: 2017-02-06 11:25:24
*/

'use strict';

var data=[
	{title:"js",cont:"Lorem i on Lorem ipsum dolor sit amet, <colorem>   Lorem ipsum dolor sit amet, consectetur adipisicing elit. Perspiciatis nihil dolorem iste quasi dolores natus perferendis eveniet eius neque molestias fugit doloremque a tempora, asperiores voluptatem adipisci ipsum nisi? Adipisci? </colorem>nsectetur <adipisiclorem>   Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptatem cupiditate, voluptatibus, rem dignissimos ex, neque nostrum ullam dolorem provident reprehenderit soluta! Reprehenderit corporis architecto consequuntur obcaecati, perspiciatis iusto, possimus dignissimos. </adipisiclorem>ing elit. Quasi doloribus ullam illo ut porro corporis sapiente at modi harum debitis! Est libero cumque voluptatum dignissimos? Fuga a sint, ad ea. nesciunt eum consectetur"},
	{title:"js",cont:"Lorem i on Lorem ipsum dolor sit amet, <colorem>   Lorem ipsum dolor sit amet, consectetur adipisicing elit. Perferendis cupiditate nostrum voluptatibus dicta harum, laboriosam maxime exercitationem magni, expedita minus aliquid magnam animi reiciendis, fuga iure blanditiis voluptates dolorum quae. </colorem>nsectetur adipisicing elit. Atque omnis, consequuntur numquam facilis eius cumque quisquam! Quisquam atque perferendis temporibus sunt enim dolore at blanditiis. Cum aliquid asperiores expedita inventore. nesciunt eum consectetur"},
	{title:"js",cont:"Lorem i on Lorem ipsum dolor sit amet, <conslorem>   Lorem ipsum dolor sit amet, consectetur adipisicing elit. Enim inventore iusto, incidunt placeat, dignissimos iure dolor dolores delectus laudantium suscipit magnam, rem obcaecati vel, natus sed animi quasi deleniti in. </conslorem>ectetur adipisicing elit. Asperiores repellendus, amet dolorem expedita quia temporibus laboriosam adipisci ipsa magni, aperiam voluptate vel aspernatur. Reiciendis maiores architecto totam blanditiis, exercitationem eaque. nesciunt eum consectetur"},
	{title:"js",cont:"Lorem i on Lorem ipsum dolor sit amet, <colorem>   Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iure quaerat, quos necessitatibus voluptatem culpa porro voluptatum impedit eum aperiam voluptas, enim dolores laboriosam excepturi! Eius vel illo mollitia, perspiciatis deserunt! </colorem>nsectetur adipisicing elit. Necessitatibus natus doloremque reiciendis sit, veniam, tempora illum voluptatibus facilis, et unde sint quo officiis saepe vitae. Corporis est, eos voluptate delectus. nesciunt eum consectetur"},
	{title:"js",cont:"Lorem i on Lorem ipsum dolor sit amet, <conslorem>   Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloremque similique tempore fugit vitae, ipsam dignissimos in laboriosam harum consectetur necessitatibus labore adipisci, incidunt asperiores omnis error voluptatum minus minima natus. </conslorem>ectetur adipisicing elit. Et, officiis iste at nobis autem sunt dolor hic velit deleniti qui inventore consequatur deserunt neque consectetur tempore, esse voluptatem, repellat eum? nesciunt eum consectetur"},
	{title:"js",cont:"Lorem i on Lorem ipsum dolor sit amet, consectetur <adipisilorem>   Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nihil ipsa maxime, recusandae earum nostrum eveniet optio, aliquam provident, beatae minus dignissimos veritatis eius labore, molestias corporis adipisci quibusdam totam architecto. </adipisilorem>cing elit. Ex ea et reprehenderit! Totam cum nemo consectetur sequi quo quibusdam, velit sunt quas, quia ipsam sint ea eum id iste minima. nesciunt eum consectetur"},
	{title:"js",cont:"Lorem i on Lorem ipsum dolor sit amet, <consectetlorem>   Lorem ipsum dolor sit amet, consectetur adipisicing elit. Neque mollitia ab, cumque et animi dolor alias illo saepe non at porro voluptas! Sunt facere corporis earum odio explicabo rerum. Totam! </consectetlorem>ur adipisicing elit. Quisquam debitis illum expedita dolorum, iste nam at totam odit atque facilis dolores beatae nisi maxime corporis ullam quae, voluptatem esse perspiciatis. nesciunt eum consectetur"},
	{title:"js",cont:"Lorem i on Lorem ipsum dolor sit amet, <conselorem>   Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum tempora, asperiores veritatis dolorem! Iure suscipit autem sed sint odit minima minus, fuga fugiat voluptate esse, rem dolores laborum, sequi quasi? </conselorem>ctetur adipisicing elit. Obcaecati quos atque minus, mollitia dicta similique natus at corporis. Modi soluta eos harum ipsum, sed ducimus optio non nulla earum similique. nesciunt eum consectetur"},

];
